services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    labels:
      org.springframework.boot.jdbc.parameters: currentSchema=application
    volumes:
      - ./docker/postgresql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./docker/postgresql/db-data:/var/lib/postgresql/data
